% TIMEFORMAT='%3R'; { time (exec 2>&1; '/Applications/Isabelle2015.app/Contents/Resources/Isabelle2015/src/HOL/Tools/ATP/scripts/remote_atp' -s LEO-II---1.6.2 -t 30 '/Users/cbenzmueller/.isabelle/Isabelle2015/prob_remote_leo2_1' ) ; }
% This file was generated by Isabelle (most likely Sledgehammer)
% 2015-12-16 13:08:11.037

% Could-be-implicit typings (1)
thf(ty_n_t__QML____S4__Oi, type,
    qML_i : $tType).

% Explicit typings (2)
thf(sy_c_QML__S4_Or, type,
    qML_r : qML_i > qML_i > $o).
thf(sy_v__092_060phi_062, type,
    phi : qML_i > $o).

% Conjectures (1)
thf(conj_0, conjecture,
    ((![W : qML_i]: ((~ ((phi @ W))) | (?[X : qML_i > $o]: ((X @ W) & (![V : qML_i]: ((~ ((qML_r @ W @ V))) | ((![Va : qML_i]: ((~ ((qML_r @ V @ Va))) | (~ ((X @ Va))))) | (![Xa : qML_i > $o]: ((~ ((Xa @ V))) | (?[Va2 : qML_i]: ((qML_r @ V @ Va2) & ((?[Vb : qML_i]: ((qML_r @ Va2 @ Vb) & (Xa @ Vb))) & (phi @ Va2))))))))))))))).
